# Model arguments
model_name_or_path: google/gemma-7b
model_revision: main
tokenizer_name_or_path: philschmid/gemma-tokenizer-chatml # Custom tokenizer with <|im_start|> and <|im_end|> tokens
torch_dtype: bfloat16
use_flash_attention_2: true

# LoRA arguments
lora_r: 8
use_peft: true
lora_target_modules:
- k_proj
- v_proj

# Data training arguments
dataset_mixer:
  chansung/merged_ds_coding: 1.0
dataset_splits:
- train_sft
- test_sft
preprocessing_num_workers: 12

# SFT trainer config
per_device_train_batch_size: 64
num_train_epochs: 32
max_steps: -1
output_dir: "./output"
optim: "adafactor"
logging_steps: 1
dataloader_drop_last: True
max_seq_length: 1024
dataset_kwargs:
  add_special_tokens: false  # We already wrap <bos> and <eos> in the chat template
  append_concat_token: false # No need to add <eos> across samples
#tpu_num_cores: 8